version: '3.8'

services:

  mysql-usuario:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mysql-usuarios
      MYSQL_USER: myuser
      MYSQL_PASSWORD: password
    ports:
      - "3310:3306"
    networks:
      - ms-network
    volumes:
      - mysql_data:/var/lib/mysql

  mysql-ubicacion:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mysql-ubicaciones
      MYSQL_USER: myuser
      MYSQL_PASSWORD: password
    ports:
      - "3309:3306"
    networks:
      - ms-network
    volumes:
      - mysql_data:/var/lib/mysql    

  mysql-notificacion:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mysql-notificaciones
      MYSQL_USER: myuser
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    networks:
      - ms-network
    volumes:
      - mysql_data:/var/lib/mysql  

  mysql-mascota:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mysql-mascotas
      MYSQL_USER: myuser
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    networks:
      - ms-network
    volumes:
      - mysql_data:/var/lib/mysql  

  mysql-difusion:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mysql-difusiones
      MYSQL_USER: myuser
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - ms-network
    volumes:
      - mysql_data:/var/lib/mysql 

  ms-usuarios:
    image: alexsander1234/ms-usuarios:latest
    ports:
      - "8180:8180"
    networks:
      - ms-net
    depends_on:
      - mysql-usuario
    deploy:
      replicas: 3

  ms-ubicacion:
    image: alexsander1234/ms-ubicacion:latest
    ports:
      - "8080:8180"
    networks:
      - ms-net
    depends_on:
      - mysql-ubicacion
    deploy:
      replicas: 3

  ms-notificacion:
    image: alexsander1234/ms-notificacion:latest
    ports:
      - "8182:8180"
    networks:
      - ms-net
    depends_on:
      - mysql-notificacion
    deploy:
      replicas: 3

  ms-mascota:
    image: alexsander1234/ms-mascota:latest
    ports:
      - "8183:8180"
    networks:
      - ms-net
    depends_on:
      - mysql-mascota
    deploy:
      replicas: 3

  ms-difusion:
    image: alexsander1234/ms-difusion:latest
    ports:
      - "8181:8180"
    networks:
      - ms-net
    depends_on:
      - mysql-difusion
    deploy:
      replicas: 3

networks:
  ms-net:
    driver: overlay
    attachable: true
  ms-network:

volumes:
  mysql_data: